### ISSUE TITLE
Api key issue

### ISSUE THREAD

**Issue by Saddam1022** [Dev-Shankar-Paul/Smart_Farming#15]
Will you please share the API key??

**Comment by heyitsdsp** [comment]
You need to go to [IpInfo](https://ipinfo.io/) and sign up for an account there and then you can get your API Key from there. You can also check out [IpInfo Python](https://github.com/ipinfo/python) for more details. Hope it helps! 

The API Key is something that is unique to every user. It should always be private and shouldn't be shared with anyone.
